title: Engineering Notes
description: Personal notes for engineering software development, aircraft design and other related fields
theme: just-the-docs
color_scheme: dark

url: https://maximtyan.github.io
math: katex

# Aux links for the upper right navigation
aux_links:
  "About the author":
    - "https://maximtyan.github.io/cv/"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true
